### PR TITLE
More refactoring, and better Preview function.

### PR DESCRIPTION
**Pull request by dkosmari**
I tried to improve the Preview function. Now, by pressing "A" it will query (sequentially) all the NTP servers, and add text entries with the correction for each IP address (or error status like timeout). Then the current local clock is shown, with the calculated correction.
preview-pic
Sadly, due to WUPS limitations, it doesn't work perfectly. The new entries are not shown until the user either tries to scroll the screen ("DOWN" then "UP"), or exit then reenter the Preview. After they new entries are shown by WUPS, they seem to update correctly when pressing "A".
And since I had to implement a "text item" element from scratch, I also decided to re-implement the "bool" and "int" items. By pressing "X" (actually "Y" because WUPS swaps the "X" and "Y" buttons for some reason) my own items can also restore the value that was loaded from the config file. Besides the extra functionality, from the code perspective, they're much more convenient to use, automatically updating the config file when changing value, and require no explicit error handling (everything is exception-safe.)

### CODE REVIEW

**Comment by Nightkingale** [comment]
Hey again, thank you so much!

This seems pretty sweet! For whatever reason, I'm experiencing a crash when trying to get the preview to work, after scrolling down and back up. However, this might be due to my own negligence somehow, and I doubt it's a fault of your code. I'm going to troubleshoot when I'm back from work, so I'll keep you updated. I'm totally down for this though!

**Comment by dkosmari** [comment]
I'm experiencing the same thing when I have only one server configured. If instead have 2 or more servers, like

`"server": "0.pool.ntp.org 1.pool.ntp.org"`

then it stops crashing with the DOWN/UP inputs. I'm investigating it now.

**Comment by dkosmari** [comment]
I've narrowed it down to buggy code inside WUPS backend. The various indexes used in the rendering code are all unsigned integers, with sloppy wraparound subtractions, that sometimes makes comparisons fail. There's no way to convince the backend to recompute the category size while inside it. The only way to reliably avoid a crash is to press B to back out and re-enter the Preview.
I will just remove the individual IP text entries, and print averages for each host name instead, since I can split the servers string ahead of time.

**Comment by Nightkingale** [comment]
Sounds good to me, that approach seems fine. Thanks for narrowing it down!

**Comment by dkosmari** [comment]
I believe it's all working now. I also finished implementing the text item class, to allow text scrolling for long strings.

**Comment by Nightkingale** [comment]
Sweet, thank you so much for this! This new implementation works perfectly, makes the menu a whole lot more informative. I appreciate having to manually refresh by the way, as opposed to routinely (and unnecessarily) connecting to the servers automatically for times.

Great work, this will be included in the next potential release! Thanks again!

**Pull request merged**
